name: smart_notes
description: "An AI-powered note-taking app that records audio, processes it with AI, and displays structured notes with synchronized playback"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.1.0
  bloc: ^8.1.4
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.6.0
  pretty_dio_logger: ^1.4.0
  theme_tailor_annotation: ^3.0.2
  retrofit: ^4.4.2
  shared_preferences: ^2.3.1
  material_symbols_icons: 4.2815.1


dev_dependencies:
  auto_route_generator: ^10.1.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  retrofit_generator: '>=8.0.0 <10.0.0'
  theme_tailor: ^3.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/satoshi/Satoshi-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/satoshi/Satoshi-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Regular.ttf
          weight: 400

